version: "3"
services:
  php:
    build: .
    container_name: "apache_php"
    image: php:8.1.16-apache
    volumes:
      - ./public/:/var/www/html/
    ports:
      - 83:80
  
  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - 3307:3306

https://chatgpt.com/share/6852b715-231c-800d-b284-b94b4c14eb08