-- MySQL Script generated by MySQL Workbench
-- qua 25 jun 2025 11:03:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hamburgueria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hamburgueria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hamburgueria` ;
USE `hamburgueria` ;

-- -----------------------------------------------------
-- Table `hamburgueria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `data` DATE NOT NULL,
  `idcliente` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idvenda`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `fk_venda_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `hamburgueria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nome_real` VARCHAR(100) NULL,
  `ingredientes` VARCHAR(1000) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(1000) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`armazenamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`armazenamento` (
  `idingrediente` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idingrediente`),
  UNIQUE INDEX `idingredientes_UNIQUE` (`idingrediente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`item_venda` (
  `idvenda` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`idvenda`, `idproduto`),
  INDEX `fk_venda_has_produto_produto1_idx` (`idproduto` ASC) VISIBLE,
  INDEX `fk_venda_has_produto_venda1_idx` (`idvenda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `hamburgueria`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `hamburgueria`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(110) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hamburgueria`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hamburgueria`.`ingrediente` (
  `idproduto` INT NOT NULL,
  `idingrediente` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idproduto`, `idingrediente`),
  INDEX `fk_produto_has_armazenamento_armazenamento1_idx` (`idingrediente` ASC) VISIBLE,
  INDEX `fk_produto_has_armazenamento_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_armazenamento_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `hamburgueria`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_armazenamento_armazenamento1`
    FOREIGN KEY (`idingrediente`)
    REFERENCES `hamburgueria`.`armazenamento` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Produto 1 – Encantamento Dourado
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Encantamento Dourado', 'Clássico da Casa', 
'Pão brioche, hambúrguer bovino 150g, queijo prato, alface, tomate, cebola roxa, maionese da casa',
28.90, 'hambúrguer', 'encantamento_dourado.jpg', 
'Um clássico encantador com pão brioche, hambúrguer suculento de 150g, queijo prato, vegetais frescos e nossa maionese especial.');

-- Produto 2 – Feitiço Clássico
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Feitiço Clássico', 'Cheddar & Bacon', 
'Pão australiano, hambúrguer 180g, cheddar cremoso, bacon crocante, cebola caramelizada',
31.90, 'hambúrguer', 'feitiço_classico.jpg', 
'Uma combinação clássica de cheddar cremoso, bacon crocante e cebola caramelizada sobre pão australiano e hambúrguer 180g.');

-- Produto 3 – Trio Arcano
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Trio Arcano', 'Smash Triplo', 
'Pão de leite, 3 smash burgers de 60g, queijo americano, picles, molho especial',
34.90, 'hambúrguer', 'trio_arcano.jpg', 
'Três smash burgers de 60g com queijo americano, picles e molho especial no pão de leite: magia em cada mordida.');

-- Produto 4 – Gorgonzola Místico
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Gorgonzola Místico', 'Blue Burger', 
'Pão rústico, hambúrguer 180g, gorgonzola, rúcula, maionese de alho',
33.90, 'hambúrguer', 'gorgonzola_mistico.jpg', 
'Para os amantes do sabor marcante: hambúrguer com gorgonzola, rúcula fresca e maionese de alho no pão rústico.');

-- Produto 5 – Fogo do Deserto
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Fogo do Deserto', 'Apimentado Texano', 
'Pão brioche, hambúrguer bovino 150g, queijo muçarela, jalapeños, molho barbecue picante, onion rings',
32.90, 'hambúrguer', 'fogo_do_deserto.jpg', 
'Explosão de sabor picante com jalapeños, onion rings e molho barbecue especial sobre hambúrguer suculento.');

-- Produto 6 – Barbecue Sombrio
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Barbecue Sombrio', 'Porco Barbecue', 
'Pão brioche, hambúrguer de pernil temperado, queijo prato, coleslaw, molho barbecue',
29.90, 'hambúrguer', 'barbecue_sombrio.jpg', 
'Hambúrguer de pernil com coleslaw e molho barbecue no pão tradicional.');

-- Produto 7 – Magia do Bacon
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Magia do Bacon', 'Bacon Lovers', 
'Pão australiano, hambúrguer suíno 180g, bacon em tiras, queijo cheddar, cebola crispy, maionese defumada',
33.90, 'hambúrguer', 'magia_bacon.jpg', 
'Uma explosão de sabores com hambúrguer suíno, bacon, cheddar e maionese defumada.');

-- Produto 8 – Poção do Pântano
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Poção do Pântano', 'Pulled Pork Sandwich', 
'Pão brioche, carne suína desfiada, molho barbecue, picles, cebola roxa',
31.90, 'hambúrguer', 'pocao_pantano.jpg', 
'Sanduíche de carne suína desfiada com picles e cebola roxa no pão brioche.');

-- Produto 9 – Mineirice Mágica
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Mineirice Mágica', 'Suíno Mineiro', 
'Pão rústico, hambúrguer de linguiça artesanal, queijo minas, vinagrete, maionese de limão',
30.90, 'hambúrguer', 'mineirice_magica.jpg', 
'Hambúrguer de linguiça mineira com queijo minas e vinagrete no pão rústico.');

-- Produto 10 – Crocris da Alvorada
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Crocris da Alvorada', 'Crocante da Casa', 
'Pão de leite, filé de frango empanado, queijo cheddar, alface, maionese com ervas',
27.90, 'hambúrguer', 'crocris_alvorada.jpg', 
'Filé de frango empanado com cheddar, alface e maionese de ervas no pão de leite.');

-- Produto 11 – Fênix Flamejante
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Fênix Flamejante', 'Frango Picante', 
'Pão brioche, filé de frango grelhado com páprica, queijo muçarela, jalapeños, maionese chipotle',
30.90, 'hambúrguer', 'fenix_flamejante.jpg', 
'Frango picante grelhado com jalapeños e maionese chipotle no pão brioche.');

-- Produto 12 – Poção Refrescante de Laranja
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Poção Refrescante de Laranja', 'Suco de laranja natural', 
'Suco de laranja 100% natural', 7.90, 'bebida', 'pocao_laranja.jpg', 
'Feito com laranjas frescas e 100% naturais. Sem adição de açúcar, corantes ou conservantes.');

-- Produto 13 – Batatas Encantadas
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Batatas Encantadas', 'Batatas fritas', 
'Batatas crocantes e douradas', 10.90, 'acompanhamento', 'batatas_encantadas.jpg', 
'Batatas rústicas servidas douradas, sequinhas e bem temperadas, direto do caldeirão.');

-- Produto 14 – Verde de Elphira
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Verde de Elphira', 'Salada temperada', 
'Alface, rúcula, tomate, pepino, cebola roxa, azeite e limão', 9.90, 'acompanhamento', 'verdedeelphira.jpg', 
'Salada fresca com vegetais crocantes, temperada com azeite e limão encantados.');

-- Produto 15 – Runa Dourada
INSERT INTO produto (nome, nome_real, ingredientes, valor, tipo, foto, descricao)
VALUES ('Runa Dourada', 'Batatas rústicas', 
'Batatas rústicas assadas com alho, ervas do bosque e sal dourado', 11.90, 'acompanhamento', 'runa_dourada.jpg', 
'Batatas assadas com alho, ervas e um toque mágico de sal dourado. Crocantes por fora, macias por dentro.');
INSERT INTO armazenamento ( quantidade, nome) VALUES (20, 'hambúrguer bovino 150g');
INSERT INTO armazenamento ( quantidade, nome) VALUES (30, 'queijo prato');
INSERT INTO armazenamento ( quantidade, nome) VALUES (50, 'pão brioche');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Pão brioche');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Hambúrguer bovino 150g');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Queijo prato');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Alface');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Tomate');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Cebola roxa');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Maionese da casa');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Pão australiano');
INSERT INTO armazenamento ( quantidade, nome) VALUES (100, 'Hambúrguer 180g');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Cheddar cremoso');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Bacon crocante');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Cebola caramelizada');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Pão de leite');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Smash burger 60g');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Queijo americano');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Picles');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Molho especial');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Pão rústico');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Gorgonzola');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Rúcula');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Maionese de alho');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Queijo muçarela');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Jalapeños');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Molho barbecue picante');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Onion rings');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Hambúrguer de pernil temperado');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Coleslaw');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Molho barbecue');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Hambúrguer suíno 180g');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Bacon em tiras');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Queijo cheddar');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Cebola crispy');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Maionese defumada');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Carne suína desfiada');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Hambúrguer de linguiça artesanal');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Queijo minas');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Vinagrete');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Maionese de limão');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Filé de frango empanado');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Maionese com ervas');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Filé de frango grelhado com páprica');
INSERT INTO armazenamento ( quantidade, nome) VALUES ( 100, 'Maionese chipotle');

-- Produto 1: Encantamento Dourado
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 1, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 2, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 3, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 4, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 5, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 6, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (1, 7, 1);

-- Produto 2: Feitiço Clássico
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (2, 8, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (2, 9, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (2, 10, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (2, 11, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (2, 12, 1);

-- Produto 3: Trio Arcano
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (3, 13, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (3, 14, 3);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (3, 15, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (3, 16, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (3, 17, 1);

-- Produto 4: Gorgonzola Místico – Blue Burger (idproduto = 4)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (4, 18, 1); -- Pão rústico
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (4, 9, 1);  -- Hambúrguer 180g
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (4, 19, 1); -- Gorgonzola
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (4, 20, 1); -- Rúcula
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (4, 21, 1); -- Maionese de alho

-- Produto 5: Fogo do Deserto – Apimentado Texano (idproduto = 5)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 1, 1);  -- Pão brioche
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 2, 1);  -- Hambúrguer bovino 150g
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 22, 1); -- Queijo muçarela
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 23, 1); -- Jalapeños
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 24, 1); -- Barbecue picante
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (5, 25, 1); -- Onion rings

-- Produto 6: Barbecue Sombrio – Porco Barbecue (idproduto = 6)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (6, 1, 1);  -- Pão brioche (assumido padrão)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (6, 26, 1); -- Hambúrguer de pernil temperado
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (6, 3, 1);  -- Queijo prato
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (6, 27, 1); -- Coleslaw
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (6, 28, 1); -- Molho barbecue

-- Produto 7: Magia do Bacon – Bacon Lovers (idproduto = 7)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 8, 1);  -- Pão australiano
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 29, 1); -- Hambúrguer suíno 180g
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 30, 1); -- Bacon em tiras
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 31, 1); -- Queijo cheddar
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 32, 1); -- Cebola crispy
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (7, 33, 1); -- Maionese defumada

-- Produto 8: Poção do Pântano – Pulled Pork Sandwich (idproduto = 8)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (8, 1, 1);  -- Pão brioche
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (8, 34, 1); -- Carne suína desfiada
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (8, 28, 1); -- Molho barbecue
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (8, 16, 1); -- Picles
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (8, 6, 1);  -- Cebola roxa

-- Produto 9: Mineirice Mágica – Suíno Mineiro (idproduto = 9)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (9, 18, 1); -- Pão rústico
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (9, 35, 1); -- Hambúrguer de linguiça artesanal
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (9, 36, 1); -- Queijo minas
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (9, 37, 1); -- Vinagrete
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (9, 38, 1); -- Maionese de limão

-- Produto 10: Crocris da Alvorada – Crocante da Casa (idproduto = 10)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (10, 13, 1); -- Pão de leite
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (10, 39, 1); -- Filé de frango empanado
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (10, 31, 1); -- Queijo cheddar
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (10, 4, 1);  -- Alface
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (10, 40, 1); -- Maionese com ervas

-- Produto 11: Fênix Flamejante – Frango Picante (idproduto = 11)
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (11, 1, 1);  -- Pão brioche
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (11, 41, 1); -- Filé de frango grelhado com páprica
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (11, 22, 1); -- Queijo muçarela
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (11, 23, 1); -- Jalapeños
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (11, 42, 1); -- Maionese chipotle

INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (12, 43, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (13, 44, 1);
INSERT INTO ingrediente (idproduto, idingrediente, quantidade) VALUES (14, 45, 1);

-- INSERTs para cliente

INSERT INTO cliente (nome, telefone, endereco, email) VALUES ('Sr. Thomas Melo', '62 93920 1593', 'Área Emanuelly da Conceição, 4, Beija Flor, 73605756 Aragão de Jesus / GO', 'thomasmelo@gmail.com');
INSERT INTO cliente (nome, telefone, endereco, email) VALUES ('Francisco Peixoto', '62 98396 0409', 'Núcleo de Ferreira, Vila Pinho, 74581-047 Gonçalves do Sul / GO', 'francisco_peixoto@gmail.com');
INSERT INTO cliente (nome, telefone, endereco, email) VALUES ('Diego Ferreira', '62 96873 7597', 'Estrada de Farias, 42, Nova Suíça, 45018640 Aragão / GO', 'diego.ferreira14@gmail.com');
INSERT INTO cliente (nome, telefone, endereco, email) VALUES ('Carolina Aragão', '62 98582 0028', 'Distrito de Silva, 7, Vila Santo Antônio, 40888427 Barbosa de Almeida / GO', 'carolina__aragao69@gmail.com');
INSERT INTO cliente (nome, telefone, endereco, email) VALUES ('Alícia Oliveira', '62 91034 2149', 'Estação de Ramos, 84, Bernadete, 48402260 da Mota de Minas / GO', 'aliciaoliveira1@gmail.com');
-- INSERTs para usuario


INSERT INTO usuario ( email, senha, nome, tipo) VALUES ( 'cecilia50@ferreira.br', 'b6J+5nLk$3', 'Camila Peixoto', 'admin');
INSERT INTO usuario ( email, senha, nome, tipo) VALUES ( 'pedro-lucasda-mota@gmail.com', 'F2ccGSLl#p', 'Vitor Gabriel Viana', 'atendente');
INSERT INTO usuario ( email, senha, nome, tipo) VALUES ( 'zda-mata@gmail.com', 'W6Q9D!s3_@', 'Kevin Oliveira', 'cozinha');
-- INSERTs para venda

INSERT INTO venda ( valor_final, observacao, data, idcliente, status)
VALUES (44.63, 'Accusantium vel dolore non quae blanditiis.', '2025-06-18', 1, 'concluída');

INSERT INTO venda ( valor_final, observacao, data, idcliente, status)
VALUES (65.41, 'Omnis natus dolorem similique fugit doloremque.', '2025-06-20', 1, 'cancelada');

INSERT INTO venda ( valor_final, observacao, data, idcliente, status)
VALUES ( 69.74, 'Earum error quod fugit fuga voluptatem.', '2025-06-09', 3, 'concluída');

INSERT INTO venda ( valor_final, observacao, data, idcliente, status)
VALUES ( 43.89, 'Qui at molestias reprehenderit recusandae odio.', '2025-06-07', 5, 'concluída');

INSERT INTO venda ( valor_final, observacao, data, idcliente, status)
VALUES ( 84.09, 'Praesentium consectetur perferendis suscipit omnis sunt.', '2025-06-10', 4, 'concluída');
